# Generated by Django 3.1.6 on 2022-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sangeet', '0003_watchlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
